
days = ["Monday 17", "Tuesday 18"]

[talks]

[talks.1_09_00]
title = "Coffee and bagels"
type = "organization"

[talks.1_09_30]
type = "organization"

[talks.1_10_00]
title = "Introduction and welcome"
speaker = "Oscar Dowson"

[talks.1_10_15]
speaker = "Miles Lubin"
title = "The state of JuMP"

[talks.1_10_45]
speaker = "Joaquim Dias Garcia"
title = "ApplicationDrivenLearning.jl a framework to train forecast models with application-driven cost functions"

[talks.1_11_00]
speaker = "Alexis Montoison"
title = "Revisiting sparse matrix coloring and bicoloring"

[talks.1_11_30]
speaker = "Julian Hall"
title = "What's new in HiGHS, and thanks to JuMP for its support!"

[talks.1_12_00]
title = "Self-catered Lunch. There are numerous restaurants and cafes nearby"
type = "break"

[talks.1_12_30]
type = "break"

[talks.1_14_00]
speaker = "Yuwen Chen"
title = "CuClarabel: GPU Acceleration for a Conic Optimization Solver"

[talks.1_14_30]
speaker = "Alexis Montoison"
title = "MadIPM.jl"

[talks.1_15_00]
speaker = "Michael Saunders"
title = "GPU Implementation of Algorithm NCL"

[talks.1_15_30]
speaker = "Joaquim Dias Garcia"
title = "Open energy models: benchmarking, profiling and debugging tool for JuMP"

[talks.1_16_00]
speaker = "James Glynn"
title = "TIMES2JuMP -  Learnings from IEA-ETSAP feasibility study of migrating the TIMES code to Julia JuMP."

[talks.1_16_30]
speaker = "Harley Mackenzie"
title = "Lessons from using JuMP in HARD software"

[talks.1_17_00]
title = "Dinner at Good George"
type = "organization"

[talks.2_09_00]
title = "Coffee and bagels"
type = "organization"

[talks.2_09_30]
speaker = "Oscar Dowson"
title = "The life and times of SDDP.jl"

[talks.2_10_00]
speaker = "Beno√Æt Legat"
title = "Large Scale JuMP Models with Constraint Generators"

[talks.2_10_30]
speaker = "Dimitri Alston"
title = "Automatic Generation of JuMP.jl Constraints from ModelingToolkit.jl Models"

[talks.2_11_00]
speaker = "Thibaut Cuvelier"
title = "Unlocking the Power of Google OR-Tools with MathOptInterface.jl"

[talks.2_11_30]
speaker = "Axel Navarro"
title = "JuLS : A Julia Local Search Solver"

[talks.2_12_00]
speaker = "Robby Parker"
title = "Optimizing over trained neural networks with MathOptAI.jl"

[talks.2_12_30]
title = "Self-catered Lunch. There are numerous restaurants and cafes nearby"
type = "break"

[talks.2_14_00]
speaker = "James Foster"
title = "JuMP on demand: Creating your own compute cluster for solving optimisation problems"

[talks.2_14_30]
speaker = "Joshua Pulsipher"
title = "The State of InfiniteOpt.jl"

[talks.2_15_00]
speaker = "Oscar Dowson"
title = "MathOptInterface: a comprehensive overview"

[talks.2_15_30]

[talks.2_16_00]
title = "Wrap up and thanks"
type = "organization"
