
days = ["Sunday 31", "Monday 1"]

[talks]

[talks.1_09_00]
title = "Coffee"
type = "organization"

[talks.1_09_30]
type = "organization"

[talks.1_10_00]
title = "Introduction and welcome"
speaker = "Oscar Dowson"

[talks.1_10_30]
title = "Talks"

[talks.1_11_00]

[talks.1_11_30]

[talks.1_12_00]
title = "Lunch"
type = "break"

[talks.1_12_30]
type = "break"

[talks.1_13_00]
type = "break"

[talks.1_13_30]
type = "break"

[talks.1_14_00]
title = "Talks"

[talks.1_14_30]

[talks.1_15_00]

[talks.1_15_30]

[talks.1_16_00]

[talks.1_16_30]

[talks.1_17_00]
title = "Dinner"
type = "organization"

[talks.2_09_00]
title = "Coffee"
type = "organization"

[talks.2_09_30]
title = "Talks"

[talks.2_10_00]

[talks.2_10_30]

[talks.2_11_00]

[talks.2_11_30]

[talks.2_12_00]
title = "Lunch"
type = "break"

[talks.2_12_30]
type = "break"

[talks.2_13_00]
type = "break"

[talks.2_13_30]
type = "break"

[talks.2_14_00]
title = "Talks"

[talks.2_14_30]

[talks.2_15_00]

[talks.2_15_30]

[talks.2_16_00]

[talks.2_16_30]
title = "Wrap up and thanks"
type = "organization"

[talks.2_17_00]
type = "organization"
